package com.bank.islamic.retakafularrangement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Retakaful Arrangement
 *
 * Business Area:      Takaful and Shared Operations
 * Business Domain:    Takaful
 * Functional Pattern: Manage
 * Asset Type:         Retakaful Treaty
 * Control Record:     Retakaful Treaty Management Plan
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Retakaful Arrangement — BIAN Semantic API")
                .description("Service Domain 'Retakaful Arrangement' (Manage pattern) "
                        + "operating on the 'Retakaful Treaty Management Plan' control record.")
                .version("0.1.0"));
    }
}
